# Generated by Django 6.0.4 on 2026-04-12 17:39

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0002_remove_elevatorreport_user_id_building_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='buildings_app.building')),
            ],
            options={
                'verbose_name_plural': 'Building News',
                'indexes': [models.Index(fields=['building', 'relevance_score'], name='buildings_a_buildin_39e5c0_idx')],
            },
        ),
    ]
