# Generated by Django 6.0.4 on 2026-04-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0011_councildistrict_committees'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='management_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
